name: Deploy LayoutPro para Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Enviar arquivos para intranet
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do repositório
        uses: actions/checkout@v4

      - name: Enviar arquivos para a Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
